### PR TITLE
Check GCC version on Ubuntu

### LINKED ISSUE #1633: Build with fails with gcc-5
### System information

* Operating system: Ubuntu 17.10
* Compiler version: version 5.4.1 20171010 (Ubuntu 5.5.0-1ubuntu1)
* CMake version: 3.9.1
* CMake arguments:  -DUSE_GLOO=OFF
* Relevant libraries/versions (e.g. CUDA): 
CUDA version        : 8.0
CuDNN version       : 6.0.21
OpenCV version      : 3.3.1

### CMake summary output

```
******** Summary ********
[ 10%] Building CXX object caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o
In file included from /home/admin/Downloads/caffe2/caffe2/perfkernels/common_avx.cc:21:0:
/home/admin/Downloads/caffe2/caffe2/core/common.h:203:12: error: ‘std::to_string’ has not been declared
 using std::to_string;
            ^
/home/admin/Downloads/caffe2/caffe2/core/common.h:204:12: error: ‘std::stoi’ has not been declared
 using std::stoi;
            ^
/home/admin/Downloads/caffe2/caffe2/core/common.h:205:12: error: ‘std::stod’ has not been declared
 using std::stod;
            ^
caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/build.make:62: the rule for target „caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o“ failed
```

### PR DESCRIPTION
**Pull request by pietern**
Thanks to @feldim2425 we know that GCC 5 in Ubuntu 17.04 and later
doesn't define the macro _GLIBCXX_USE_C99 and by extension the
std::to_string, std::stoi, and std::stod functions (and probably
more). Instead of avoiding using these functions, we simply recommend
people to use GCC 6 or higher on the newer Ubuntu versions where GCC 5
doesn't work.

As a side note, CUDA 8.0 is compatible with GCC up to version 5. This
implies that compiling Caffe2 with CUDA on Ubuntu >= 17.10 implies
using CUDA >= 9.0. If you need to compile with CUDA 8.0 and are on
Ubuntu, you are stuck on version 16.04 or lower.

I verified this fix by running cmake on Ubuntu 17.10 with
-DCMAKE_CXX_COMPILER=/usr/bin/g++5 and observing the fatal error.

This closes #1633.

### CODE REVIEW

**Comment by pietern** [comment]
@slayton58 FYI

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
Backing out the cmake_push_check_state/cmake_pop_check_state change. Moving MiscCheck.cmake around apparently has broader consequences that should be dealt with separately.

**Review by Yangqing — APPROVED** [review]
